export const ADD_QUOTATION = 'ADD_QUOTATION';
export const GET_QUOTATION = 'GET_QUOTATION';
export const DELETE_QUOTATION = 'DELETE_QUOTATION';
export const QUOTATION_LOADING = 'QUOTATION_LOADING';
export const QUOTATION_NOT_FOUND = 'QUOTATION_NOT_FOUND';
export const GET_QUOTATIONS = 'GET_QUOTATIONS';