export const ADD_INVOICE = 'ADD_INVOICE';
export const GET_INVOICE = 'GET_INVOICE';
export const DELETE_INVOICE = 'DELETE_INVOICE';
export const INVOICE_LOADING = 'INVOICE_LOADING';
export const INVOICE_NOT_FOUND = 'INVOICE_NOT_FOUND';
export const GET_INVOICES = 'GET_INVOICES';