export const ADD_DELIVERY_ORDER = 'ADD_DELIVERY_ORDER';
export const GET_DELIVERY_ORDER = 'GET_DELIVERY_ORDER';
export const DELETE_DELIVERY_ORDER = 'DELETE_DELIVERY_ORDER';
export const DELIVERY_ORDER_LOADING = 'DELIVERY_ORDER_LOADING';
export const DELIVERY_ORDER_NOT_FOUND = 'DELIVERY_ORDER_NOT_FOUND';
export const GET_DELIVERY_ORDERS = 'GET_DELIVERY_ORDERS';