export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const DELETE_APPOINTMENT = 'DELETE_APPOINTMENT';
export const APPOINTMENT_LOADING = 'APPOINTMENT_LOADING';
export const APPOINTMENT_NOT_FOUND = 'APPOINTMENT_NOT_FOUND';
export const GET_APPOINTMENTS = 'GET_APPOINTMENTS';