export const ADD_DOCUMENT = 'ADD_DOCUMENT';
export const GET_DOCUMENT = 'GET_DOCUMENT';
export const DELETE_DOCUMENT = 'DELETE_DOCUMENT';
export const DOCUMENT_LOADING = 'DOCUMENT_LOADING';
export const DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND';
export const GET_DOCUMENTS = 'GET_DOCUMENTS';
export const UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT';
export const UPLOAD_ERRORS = 'UPLOAD_ERRORS';