export const ADD_ACTIVITY = 'ADD_ACTIVITY';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ACTIVITY_LOADING = 'ACTIVITY_LOADING';
export const ACTIVITY_NOT_FOUND = 'ACTIVITY_NOT_FOUND';
export const GET_ACTIVITYS = 'GET_ACTIVITYS';